### ISSUE TITLE
No new releases?

### ISSUE THREAD

**Issue by kiravi** [ExchangeCalendar/exchangecalendar#139]
Seems like there are more than 80 new commits, but no new releases?

**Comment by Trim** [comment]
Well, we are only two people actively contributing to this project.

I'm trying to make some patches to fix the most urgent bugs and @advancingu manage review and merging. As written in the readme, we are making best effort to keep the project living, but we don't have many free time :/

Note that, currently, Thunderbird have some security issues found recently due to the extension system and if they decide to use only WebExtension API I think we won't be able to migrate ExchangeCalendar to it (due to the restrictions for security; this extension do a lot of modifications in Thunderbird/Lightning).

**Comment by umesh3034** [comment]
How can we help? Can you attach/create a debug guide here, so that we can take a look? I am not a expert in JS, but i can manage to fix issues if debug methods are clear..

**Comment by oaxjogi** [comment]
I would also help with testing. I am using the Exchange Calendar plugin on Win64 and macOS and could also test it on a SPARC Solaris 10.

**Comment by Trim** [comment]
I don't have many experience with JavaScript  and Thunderbird tools for developpement.

What I've used up to now is the "Devlopper tools" from Firefox that are now also activated in Thunderbird. Although, I wasn't able to use the Inspector from these tools to inspect XUL structure. To do that, I'm using the [DOM Inspector for Thunderbird](https://addons.mozilla.org/en-US/thunderbird/addon/dom-inspector-6622/) (you can force the installation of the module, even if it doesn't support the current Thunderbird release).

To understand a bit more how XUL and JavaScript work together, I've found last summer the "Rapid Application Development with Mozilla" book which is downloadable [here](http://www.informit.com/content/downloads/perens/0131423436_pdf.zip) (source from [SlashDot](https://news.slashdot.org/story/04/04/14/0135236/rapid-application-development-with-mozilla)).

The Exchange Web Service documentation is available on the Microsoft web sites: for example, the article for [FindItem](https://msdn.microsoft.com/en-us/library/office/aa566107(v=exchg.150).aspx).

In my opinion, when current pull requests will be merged to close #80 "Update code tree", the next bug to resolve will be to update code for the coming ESR (59, autumn 2018) which will require to work on issue #136 (see the Addons Guide 57 quoted in the issue report).

---

In my opinion, exchangecalendar project is suffering of several difficulties:

* The code is really big: it modifies almost all parts of Thunderbird/Lightning: emails handling, calendars, contacts, global search indexer, a lot of dialogs,...
* The code is old and so it's using old  JavaScript tooling:
  * it's using old JavaScript tools: for example, with EcmaScript 6, now we can write more secure code by using local variables (with let) and we can also use a lighter way to write JavaScript prototypes by using a coding style borrowed from object oriented programming
  * there's a ton of callbacks everywhere and so the structure of the code is really hard to follow. Modern Promises can help to continue using callbacks for asynchronous tasks and to have a simpler to read code structure.
  * It's using directly XMLHTTPRequest to be able to manage redirections and weird Exchange Web Service stuff (I don't remember exactly now, but its about NTLM authentication and/or autodiscovery). If we were able to use Fetch API (certainly by supporting less Exchange weird stuff) it would be more efficient as it uses Service Workers which allows to run heavy tasks out of the main thread (yes it could solve a lot of perf issues).
* Lightning code is moving from XUL dialogs to HTML/React dialogs
* Thunderbird will have to do a lot of work on its extension architecture according to a recent audit made with Posteo: https://posteo.de/en/blog/security-warning-for-thunderbird-users-and-enigmail-users-vulnerabilities-threaten-confidentiality-of-communication . I think the simpler for them is to remove XUL extensions and use only pure WebExtensions: if that's the case, I don't see how exchancalendar will be able to continue to modify all the stuff (see first point).

To summary, I think the project is unfortunately in a dead end: its past is too important (the code is big and hard to maintain) and the future of Thunderbird / Lightning will certainly requires a lot of modifications :/

**Comment by umesh3034** [comment]
Hey, i understand the complexities. How difficult would it be to create WebExtensions for the same wrt to this Add-on?

**Comment by Trim** [comment]
The issue with WebExtension is that we'll need APIs to be able to do modifications on Thunderbird and Lightning (WebExtensions are sandboxed).

Currently, XUL extensions are able to modify everything in the UI and in the background. With WebExtension you are limited to modifications allowed by the Thunderbird developpers: it was a hard requirement to Firefox engine to be able to use multiprocess engine.

I hope that, if Thunderbird will allow only WebExtensions, they will provide API to add calendar and contacts provider at least.

IIRC that won't be enough, because the extension modify too the mail view to add the ability to manage Exchange shares and invitations.

**Comment by BenjamenMeyer** [comment]
Created #136 per the webextensions stuff; but perhaps the group needs to get proactive with Thunderbird devs to ensure that our needs are met for any WebExtension functionality or that XUL is maintained going forward with Thunderbird, much like the TabGroups/Pandora folks were with Firefox (which while a very slow response, did result in changes to Firefox). I'm thinking the Thunderbird folks will _likely_ be more receptive than the Firefox folks were though.

**Comment by mrueg** [comment]
I would welcome a new beta release of the current 4.0 branch, especially since it would include this fix (https://github.com/ExchangeCalendar/exchangecalendar/pull/118).

**Comment by Trim** [comment]
Finally, I took time to create the big PR #143 

It will be interesting to merge it, push and fetch new translations and make a new beta release.

Yes I propose again a beta release, because it move a lot of code, rename name spaces (removing the too common 'resource://interfaces' name space which I hope will fix TB UI errors) and should fix password shown in dialog boxes.

If you are ok, I'll merge it myself to speed up the process. If not, please comment here or on the PR #143 (if there's no answer, I'll merge it on 4th February 2018).

**Comment by ydelau** [comment]
For all the fixed issues, I’m eager to put my hands on this new release, so I’m ok to speed up the process ! :-) anyway it’s labeled Beta ;-)

**Comment by advancingu** [comment]
Closing deprecated issues.
