### ISSUE TITLE
transfer ownership instead of forking?

### ISSUE THREAD

**Issue by monperrus** [ExchangeCalendar/exchangecalendar#16]
It took me one hour to find https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v4.0.0-beta1

Instead of forking Ericsson/exchangecalendar what about transfer ownership to the new organization ExchangeCalendar.

All links will still work, issues will be kept.

**Comment by advancingu** [comment]
Due to the lack of reaction from the original repository owner in https://github.com/Ericsson/exchangecalendar/issues/598 I highly doubt this would be possible from a practical perspective alone. Also, Ericsson is a large corporation where chances are effectively zero that they would let external people run anything under their name.
