### ISSUE TITLE
TbSync + EWS ?

### ISSUE THREAD

**Issue by jobisoft** [ExchangeCalendar/exchangecalendar#182]
Hi,

I am John, the developer of TbSync, an AddOn for Thunderbird for Exchange ActiveSync. It has been mentioned multiple times in this issue section and has been called an alternative for your EWS provider AddOn.

**It is not, because it is using EAS (ActiveSync) and not EWS (WebServices) and is not as powerful as your AddOn: It does not allow access to shared resources on Microsoft Exchange Server, because EAS does not support that (some third party servers like Kopano do support that, but not those from Microsoft).**

I created it, because most of those third party serves ONLY support EAS. So your AddOn (or its parents) did not work for me.

TbSync is ready for TB61, it is bootstrapped. I also wrote my own OverlayManager to be able to do XUL overlays, even though that has been removed from Thunderbird Core. I know that the Lightning maintainer also works on something like this, which will probably become part of Thunderbird, but it is not yet avail, so I wrote my own.

Now the important stuff: TbSync has been designed to be provider driven, that is why it has a generic name.  So it would be possible to add EWS support (as git submodule). That would be done in 3 phases:

1. I would provide the GUI hooks, so it will be possible to add an EWS account, you will add autodiscover and the EWS API so the user can connect his*her account and view the containing resources. This would also be a feasibility test.

2. Implement the core sync logic (from server, to server, add, mod, del). This would be a pure sync implementation, no UI elements, no overlays. Just get the data from the server and create the Thunderbird objects  and the other way around (TbSync auto manages calendars and address books, the user just creates the account)

3. Get all your extra bits in, which require overlays and everything else like auto completion in address book, invites handling and so on...

You would be in charge of the EWS provider, I just hook your repository into the provider subfolder. 

Looking forward to hear from you.

**Comment by Trim** [comment]
Hello,

Well, that's really interesting: I didn't expect the overlay issue could be treated inside an extension directly.
Great 👍 

On the current ExchangeCalendar extension, I've mostly tried to hack the New account dialog and the Address book synchronization (read-only currently). So I think I could try to implement the Autodiscover / Account settings part and try to make a first implementation of the Address book synchronization (still in read-only mode).

I'll try to study how the eas provider currently work and see if I'm able to create a new provider for EWS.

I expect that almost all code of ExchangeCalendar need to be rewritten, as the code uses old JavaScript language. Althoug I think that's way more feasible with the help of TbSync which will give us a more stable interface to create overlays and to display data (before we were hacking directly the Lightning extension and it created bugs due to overriding some Lightning parts...).

To summary, next actions I'll try will be:

1. See if I well understand the TbSync interface
2. Try to add support of "EWS" for the "New Account Dialog"
3. Then try to implement a read-only AddressBook synchronizer
4. If that's ok, I'll iterate through the EWS API to integrate more and more items (but they are almost all unknown currently for me ;) )

Many thanks for your support and for your tools !

Mmhh, I've just seen TbSync license is GPLv2... I don't know if I can create a GPLv3 submodule, as currently the licences of ExchangeCalendar is GPLv3.

@advancingu have you any idea if we can do such licensing mix ? Apart this detail, do you think that will be better to work in another repository for this new code ?

I'm in favour in creation of a new repository as almost every thing will be rewritten and to clearly show to users there's something happening which will not be compatible with the current ExchangeCalendar extension.

**Comment by jobisoft** [comment]
I would suggest a new repo, for the start, I would suggest to just fork TbSync and do all the work directly inside your fork. This is still the test-if-this-will-work phase.

I do not think, that the API itself needs to be rewritten, but we will see what happens.

I will check the lic issue! What is the diff between yours and mine? Could I just upgrade?

If you want to give it a try, I will create a bare-bone-ews provider for you to start coding, just give me a few days.

**Comment by jobisoft** [comment]
For the bare-bone-ews provider I need two data structures, what do you need to store for each account, and what do you need to store for each "folder" (calendar or addressbook etc, in EAS these are called folders)?

What information is an EWS server sending during autodiscover, that need to be stored per account? With EAS for example the server sends what version and what commands he supports... Anything else or nothing at all?

Per account:
```
accountname
foldersynckey (some sort of sync key for the global folder list?)
host
user
https (if user selected http or https)
allowedEwsVersions
allowedEwsCommand
```

And per "folder":
```
folderID (some sort of unique id for that folder?)
name
type (what different type values are possible?)
synckey (some sort of synckey to store the syncstate of that folder)
```

**Comment by Mechtilde** [comment]
To the license question:

exchangecalendar is licensed under GPLv3
Tbsync is licensed under GPLv2

All parts of TbSync written by jobisoft can be upgraded to GPLv3, also the parts licensed under GPL v2+ from other committers.

Mechtilde

**Comment by advancingu** [comment]
Sorry everyone for my longer absence (see my profile for the reason why).

@jobisoft Thanks John for reaching out!

I think the general idea of using TbSync as a frontend that supports multiple adapters that handle various backends is promising. This way we won't have to worry about all the UI code and can focus on EWS communication in this project. Also, upgrading the existing EWS code (other than the UI) to match the new JS environment should be _much_ easier than rewriting the entire project even with the old codebase being in quite bad shape architecturally.

With that said, I agree with @jobisoft that figuring out what needs to be done for a prototype should be the next step. I would however not yet set up a new repository as it will split attention between this one and a new repository. Instead I suggest to create a prototype branch here. Once the mechanism to connect both projects has been figured out and in case major refactoring needs to be done to this codebase, I would revisit this question.

In fact, I believe we should simply release an official version 4 of the existing implementation soon. Afterwards, when the refactored code becomes incompatible, it can be treated as the next major version 5 in the existing repository that already has a lot of stars and links on the web.

I will also try to monitor the project a bit closer in the future to provide my input.

**Comment by jobisoft** [comment]
Agreed. 

I do not know if the git submodule approach will realy work, i think the locale files will break that approach. However, creating a build script to copy the bits from two repositories together to make the xpi file should be easy.

As soon as I have the information about the minimum datastructure, i will work on the barebone-ews-provider.

**Comment by advancingu** [comment]
Wouldn't it be possible to simply install two extensions alongside and have them communicate among each other in some form? If you bake everything into TbSync at build time you will no longer have the flexibility to fix bugs in an adapter without rolling a new TbSync release, so the more adapters you integrate, the more overhead you incur. This can quickly become a major bottleneck and in my experience this is usually not a good idea.

In the separate approach, assuming you can directly call code in another extension, this project here would offer you a well-defined interface of an agreed upon structure that you can call, so that the actual implementation behind it won't matter and can evolve independently. If calling code directly isn't possible, I assume there will be some other IPC mechanism that can be used with the same concept of abstraction. Of course this adds upfront coordination overhead but long-term this usually pays off.

**Comment by jobisoft** [comment]
With bootstrapped extensions this might not work, they are sandboxed. But we will figure that out later. I do load the tbsync object into the global scope of each window, but I have not tried to access that object from a different addon.

The multi-provider mechanism is pretty simple at the moment and nothing is fixed yet, because i do not yet use multiple providers. The main concept of the manager UI is to call predefinded functions, to init sync for example `tbsync[provider].sync(...)`. The interaction with the manager UI is done via observers (sync process etc.) and this works across addons.

Might be interesting: TbSync has a sidechannel updater, so bugfixes can be distributed fast, without having to wait for mozilla. 

From other issues I have read, you do want to get back onto AMO? The best option is of course to have a stand alone adapter/addon, independently maintained, which can hook into TbSync.

Also: My overlayManager has just been aproved by mozilla and past review!

**Comment by Trim** [comment]
Hello,

> For the bare-bone-ews provider I need two data structures, what do you need to store for each account, and what do you need to store for each "folder" (calendar or addressbook etc, in EAS these are called folders)?
>
> What information is an EWS server sending during autodiscover, that need to be stored per account? With EAS for example the server sends what version and what commands he supports... Anything else or nothing at all?

That's a good question, currently ExchangeCalendar ask to create one account by folder...

That's a bit heavy, even if there's an option to create a new account with "copy settings to sync a new folder".

If I read my settings from `about:config`, I find right now these values for one `Account+Folder` structure:

```
UserReadOnly: true/false
dbVersion: 1
disabled: true/false
ecCalendarPollInterval: 60
ecChangeKey: empty string
ecDomain: activedirectory domain, but can be empty and defined directly in the user name
ecFolderID: empty string
ecFolderIDOfShare: empty string
ecFolderbase: one value of tasks, calendar, 
ecFolderpath: a path describing exactly which folder to sync from folder base
ecMailbox: the mailbox where to find folders
ecServer: the URL of the "exchange.asmx" Web Service endpoint (https://exchange.example.com/ews/exchange.asmx)
ecUser: the active directory user which will read the mailbox
exchangePrefVersion: 1
folderClass: IPF.Task
lastMajorVersion: 15
lastMinorVersion: 1
lastServerVersion: Exchange2013
syncState: some string defined by the server
syncStateInbox: some string defined by the server
useOfflineCalendar: true/false
```

I would guess, that for the account part, we'll need these ones:

  * ecServer
  * ecDomain
  * ecUser
  * ecChangeKey (not sure!)
  * lastMajorVersion
  * lastMinorVersion
  * lastServerVersion

and for the folder part:

  * disabled
  * userReadOnly
  * ecCalendarPollInterval
  * ecFolderId
  * ecFolderIdOfShare
  * ecFolderbase
  * ecFolderpath
  * ecMailbox
  * folderClass
  * syncState
  * syncStateInbox
  * useOfflineCalendar

Altough, most of these settings seem only relevant for the ews provider and we should manage them ourself.

As suggested by @advancingu , I'll try to see if we can keep the current ExchangeCalendar code and to just make a bridge with TbSync (for the moment by directly include of ExchangeCalendar inside TbSync). It will ask a lot of work to have it working with latests Thunderbird palteform, but it should be faster than recreating things from zero.

**Comment by jobisoft** [comment]
I messed up the last update of TbSync (unrelated to this issue), so this will take all my time now. I get back to you as soon as I fixed that. 

I am planing to rewrite the hook mechanism, so that you can write a stand alone addOn as suggested by @advancingu

**Comment by jobisoft** [comment]
This is getting interesting. The prototype is working. I release the attached file (and its content) with GPL 3.0+. I do not need to be credited at all. It is obviously derived from tbSync, to get a fast start. It contains unneeded locale strings and some unneeded functions, but that can be sorted out later. 

[TbSync 0.7.10](https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-0.7.10.xpi) is looking for this external provider during startup, if you install the attached file (rename zip to xpi) it will show up in the add-account-dialog (you may have to restart thunderbird).

I would suggest to load the content of that file into a new repository or branch. You need to pick an addon name, and addon id and an addon icon and update install.rdf and chrome.manifest. 

As internal name I picked "ews4tbsync", if you want to change that as well, you have to change it everywhere.

You can re-arrange the files inside as you like. The only thing you may NOT change is the name of the object inside ews.js. It must be called "ews".

After your are done with setting up the addon, I need to update the [hook](https://github.com/jobisoft/TbSync/blob/v0.7.10/content/tbsync.jsm#L132-L138) in TbSync (or you do it in your fork of TbSync).

The provider itself is not doing much, it just provides function, locale strings and xul dialogs, which can be used by TbSync.

I will give more explanations later. It is ready for you to add autodiscover. As soon as you created a new branch/repository, I show you where.

[TbSyncEws.xpi.zip](https://github.com/ExchangeCalendar/exchangecalendar/files/2159108/TbSyncEws.xpi.zip)

**Comment by jobisoft** [comment]
Some images:
![image](https://user-images.githubusercontent.com/5830621/42230421-406ce71e-7ee9-11e8-82e8-101203a806fb.png)

And the dialog which is injected from the external provider addon:
![image](https://user-images.githubusercontent.com/5830621/42230483-698e0600-7ee9-11e8-85fa-b1eb40f7d906.png)

All the text you can see is actually from the locale file of the external provider addon. The main TbSync has german locale files, but the provider addon only english, thats why the language changes. But this is all as expected and I am flabbergasted how easy that was.

**Comment by jobisoft** [comment]
I continued to work on the external provider prototype. It can now be loaded/unloaded independently of TbSync. Furthermore it is ready for "phase 2" as mentioned in my initial post. The prototype is simulating now a full sync cycle, that means:

 - UI integration fully working
 - DB integration fully working
 - changelog access fully working

But of course it is not talking to any server, but is making up fake data. Everytime the EWS account is synced, an new folder is "found" on the server. For each folder an actual Thunderbird object (address book or calendar) gets created. If you add items to those Thunderbird objects, they are marked as "modified" and TbSync will sync the changes, with full UI progress indication.

![image](https://user-images.githubusercontent.com/5830621/42384453-4cc741be-813a-11e8-8f5a-01c4945f1e99.png)

All is missing now is the actual EWS API.

I did reduce redundancy but still need to work on accountSettings.js, which is almost a full copy of my own version...

Latest version of the prototype can be found here:
https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSyncEws.xpi

It needs Tbsync 0.7.10.2:
https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-0.7.10.2.xpi

**What do you think about this, will you give it a try?**

**Comment by jobisoft** [comment]
I finished my work on transforming TbSync, so it can be extended by external sync provider extensions. I decided to created a repository for the EWS prototype (which is my example implementation), so it has a home:
https://github.com/jobisoft/EWS-4-TbSync

The extension and the interface should be self explanatory. More information can be found in the README of that repository. I am here, if you have any questions. Feedback would be nice.

**Comment by jobisoft** [comment]
I also released the first version of my own [sabre/dav provider for TbSync](https://github.com/jobisoft/DAV-4-TbSync/releases), which is basically a copy of EWS-4-TbSync, but it is actually doing something: It retrieves the available resources from the CalDAV/CardDAV server. So if you need a quickstart on how to actually communicate with a server, take a look at the sabre/dav provider. I use the new fetch API but you can also use a (promisified) XmlHttpRequest (as the EAS provider is doing it).

I also release a new version of the EWS provider, which improves its readability and should make it more easy to start off with.

**Comment by Trim** [comment]
Hello,

Many thanks for your work, I think we should really modify the Exchange Calendar extension to be an event / task / contact provider for TbSync.

I hopped I'll be able to take part of these changes after my holidays, but unfortunately I have to admit I won't be able to manage such big project on my free time. My issue is not with Exchange Calendar neither with TbSync extension / community, but it's about my personal life.

I need to take time for me as I'm currently in a bad mood. I don't know when I'll be in a better feeling, I know it will take some months and during this time I won't have the motivation to take part to this project.

I'm really sorry that I didn't know before and that I wasn't able to advertise the community and I hope some other JavaScript developers will take this project and make it work with TbSync and next Thunderbird releases.

Thanks everyone for your trust !

(follow will be an explication in French which is my mother language as I'm not sure of my English in the above text)

---

Hello,

Merci beaucoup pour ce travail, je pense vraiment que nous devrions modifier l'extension Exchange Calendar pour être un fournisseur d'agenda / tâche et contact pour TbSync.

J'espérais pouvoir m'occuper de ces changements après mes vacances, mais malheureusement je dois admettre que je n'en serai pas capable de gérer un tel projet sur mon temps libre. Le problème ne réside ni dans Exchange Calendar ni dans TbSync (que ce soit les communautés ou les extensions elles-même), mais c'est ma vie personnelle.

J'ai besoin de prendre du temps pour moi comme je suis actuellement un peu déprimé. Je ne sais pas quand j'irai mieux, mais je sais que ça prendra plusieurs mois et que durant ce temps je n'aurai pas la motivation de travailler sur ce projet.

Je suis vraiment désolé de ne pas m'être rendu compte avant et que je n'ai pas pu avertir la communauté plus tôt. J'espère que d'autres développeurs JavaScript pourront venir travailler sur ces changements et qu'ExchangeCalendar pourra fonctionner avec TbSync et les prochaines versions de Thunderbird.

Merci à vous tous pour votre confiance !

**Comment by jobisoft** [comment]
@Trim : Thanks for your feedback. I wish you all the best, take all the time you need to feel better again, there is nothing more important than ones personal life. 

If this project will not become a provider for TbSync, than that is fine, do not feel pressured! The time I spend on the prototype is not wasted, because I wanted to open up for others anyhow. The idea of @advancingu to actually use a stand-alone-extension, which can hook into TbSync just got me curious and I wanted to see, if that could work. 

If this project or this community wants to continue with the prototype, I will be available for help. Also, if you need changes to the API, we can get that fixed.

**Comment by advancingu** [comment]
@Trim Salut Adrien, tout d'abord merci beaucoup pour ton travail ici depuis 2017! Il n'y avait aucun autre contributeur qui a fait un tel effort et le project ne serait pas a ce place aujourd'hui sans ton travail. Alors prends ton temps pour rester et recharger. On va te souhaiter la bienvenue si un jour tu decidera de retourner.

@jobisoft Great to see that the TbSync extension approach appears to be working. I think this will be the best starting point for you to build on. I guess the most difficult part now will be to rip out all the code from this extension here so that it no longer expects to be run as a first-class add-on.

**Comment by ydelau** [comment]
@Trim Merci Adrien, un peu tardivement, mais sache que tu as su remettre
d'aplomb le projet sur lequel les utilisateurs sous GNU/Linux de mon
département comptent, et je t'en remercie ! L'important est néanmoins la
santé, donc prend soin de toi ! :)

I think the overall approach for going forward on the project is fairly
good, and if I happen to have some free time in the coming weeks I'll try
to see if I can help in any way... :)

**Comment by jobisoft** [comment]
Is office 365 working with EWS? If not I would need access to an EWS test account to try to actually go the first step and add autodiscover support.

If this works and the entire concept seems plausible, I will only be able to help creating the provider, but I will not have the time to maintain it. 

Until a final decision has been found, where to host the provider, I will continue to work on the EWS-4-TbSync repository in my github account. Everybody is invited to become a collaborator!

**Comment by jgato** [comment]
wuaauh this looks promising. But I guess, there is still no EWS provider compatible with your TbSync, isnt it @jobisoft ?

**Comment by jobisoft** [comment]
Not yet. I am currently working on DAV-4-TBSYNC, as a proof of concept, to see if the API is strong enough and to test and adjust the update/release infrastructure.

This will take 2-3 weeks, I think.

After that, I will try to add autodiscover support to the EWS prototype, to get this started. But I will not be able to finish the EWS provider on my own.



Am 07.08.18 um 10:09 schrieb Jose Gato Luis

**Comment by BenjamenMeyer** [comment]
@jobisoft if testing with O365, can you also test 2FA support? If not possible, okay - I know it wasn't before because of how some things hooked up, but that would be a huge benefit going forward if possible.

Either way, thanks for helping out on this. I love the approach suggested. Looking forward to something working going forward.

**Comment by jobisoft** [comment]
Are you talking about the azure mfa? Than this would work ONLY with O365, not with standard exchange servers? 

https://docs.microsoft.com/de-de/azure/active-directory/authentication/concept-mfa-whichversion


Which azure mfa? Server mfa or cloud mfa?

The cloud mfa supports special client passwords, for clients not supporting mfa. Would that not be enough?

**Comment by BenjamenMeyer** [comment]
@jobisoft I specifically need the O365 MFA (ADFS+Federation) myself; not sure what version we're using off-hand.

We have a work-around in place now, but it'd be nice to be able to just use MFA from the get go.

**Comment by jobisoft** [comment]
I just want to give a quick update.

The concept seems to work, but I am still waiting for the final confirmation of the thunderbird team. The proof-of-concept provider has already been [released](https://addons.thunderbird.net/de/thunderbird/addon/dav-4-tbsync/), but not yet the next version of TbSync itself, which can actually use it. That version is still pending review.

It looks like, I can only register provider AddOns in TbSync, that are listed on AMO themself, because TbSync is listed. If I "hot-link" self hosted providers, I might get removed from AMO. I am still negotiating this. 

I have found one weakness of the API, which I will fix soon.

**Comment by jobisoft** [comment]
YEAH! Accepted and officially released!
https://addons.thunderbird.net/de/thunderbird/addon/tbsync/

That version has the API fixed and knows how to handle external providers! I will now start to work on the EWS provider, stay tuned.

**Comment by advancingu** [comment]
Since this project survived the update to Thunderbird 60, I think this issue here is presently not that urgent anymore. Of course this doesn't mean that it's a bad idea to use a plug-in model, it's just that it's easier to continue maintaining the existing add-on than to do a major refactor.

As this issue also isn't actionable, I will close it to reduce clutter. I am however open to creating new issues to plan specific code changes in the future.

**Comment by jobisoft** [comment]
I agree. I am working a lot on TbSync to make it better and to get all the initial bugs out. Probably when TB68 is approaching, we can talk about this again. This is still on my agenda.

**Comment by ahsanhussain** [comment]
After migrating to 18.04 and TB 60.x (on which EWS plugin stopped working) I was desperately looking for a working solution to getting exchange server calendar on TB. Here's what worked eventually after trying everything from tbsync to davmail (which didn't work because my organization has 2FA).

1. Activated EWS service by going to the exchange.asmx link 
2. Installed lightning plugin for calendar
3. Installed latest alpha version of exchange calendar plugin from https://github.com/ExchangeCalendar/exchangecalendar/releases
4. Create a new network claendar: server url to be used is your exchange.asmx link
5. Enter domain and organization's username
6. Once you enter this server url you will have the "check server and mailbox" button available which creates the calendar after asking for login credentials.

Step 6 went a little haywire as I had to disable/re-enable the lightening and exchange pugins, and restart thunderbird a couple of times for it to get rid of wait circle, and "URL authorization failed" error.

Hope this helps someone.

**Comment by Champal** [comment]
Hi, 
One year later TB68 is here and @advancingu himself admits that updating ExchangeCalendar will be long and difficult : https://github.com/ExchangeCalendar/exchangecalendar/issues/277#issuecomment-567206858

@jobisoft Can you help with the upgrade? Maybe it's easier to focus only on the provider part?

I hope it will work because it would be a waste to lose all the work done here.
Thanks for everything.

**Comment by Mechtilde** [comment]
Hello ,

for me tbsync works very well.

It is packaged for Debian

Kind regards

Mechtilde

Am 23.12.19 um 11:42 schrieb Champal:
> Hi, 
> One year later TB68 is here and @advancingu himself admits that updating ExchangeCalendar will be long and difficult : https://github.com/ExchangeCalendar/exchangecalendar/issues/277#issuecomment-567206858
> 
> @jobisoft Can you help with the upgrade? Maybe it's easier to focus only on the provider part?
> 
> I hope it will work because it would be a waste to lose all the work done here.
> Thanks for everything.
> 

-- 
Mechtilde Stehmann
## Apache OpenOffice
## Freie Office Suite für Linux, MacOSX, Windows
## Debian Developer
## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by Champal** [comment]
> Hello , for me tbsync works very well. It is packaged for Debian Kind regards Mechtilde Am 23.12.19 um 11:42

I'm happy for you if your TbSync works on your computer with your os and your setup, sincerely.
But the subject here is EWS and to my knowledge only ExchangeCalendar is working.
TbSync was supposed to use ExchangeCalendar as provider for EWS : https://github.com/jobisoft/TbSync#where-is-this-going
Since the evolution to TB68 of ExchangeCalendar is compromised, I'll start again this topic.

**Comment by jobisoft** [comment]
Please do not fight over this. I cannot give any ETA of a EWS provider for TbSync. To my knowledge, the owl addon may help EWS users, as the latest version should support calendar.

**Comment by Champal** [comment]
If you're thinking about working on the EWS provider for TbSync it's already good news :-)

OWL, this one? https://addons.thunderbird.net/en-US/thunderbird/addon/owl-for-exchange/
It's only about OWA? Does it also work for EWS? 
The world of microsoft is so messy!  https://support.deskpro.com/en/kb/articles/what-is-the-difference-between-microsoft-owa-and-ews
I don't see what this plugin brings more, with basic Thunderbird the Office 365 mails already work. 
The OWL website is full of ... voids : https://www.beonex.com/owl/index.html
I'll try after the holidays, now let's party!

**Comment by jobisoft** [comment]
> It's only about OWA? 

I was told, it may also do EWS. Owl is also needed, if your Exchange admin disabled IMAP.

**Comment by nesuribe** [comment]
> OWL, this one? https://addons.thunderbird.net/en-US/thunderbird/addon/owl-for-exchange/
> It's only about OWA? Does it also work for EWS?
> I don't see what this plugin brings more, with basic Thunderbird the Office 365 mails already work.
> The OWL website is full of ... voids : https://www.beonex.com/owl/index.html
> I'll try after the holidays, now let's party!

They are literally the same people who bought ExQuilla, so that is where the code is coming from https://www.exquilla.com/ Weird they don't mention that in the OWL website.

I have used ExQuilla for a few years and it works flawlessly for EWS (IMAP is disabled for me), but does *not* support calendar.
