### ISSUE TITLE
Invites containing attachments don't show up in the calendar

### ISSUE THREAD

**Issue by artojarvinen** [ExchangeCalendar/exchangecalendar#210]
Other invites work. Exchange Calendar 5.0.0-alpha1, TB 60.2.1.
Thanks for maintaining the valuable plugin!

**Comment by advancingu** [comment]
@artojarvinen What do you mean by "invites"? The "still to be responded to event" in the calendar?

**Comment by gitman0** [comment]
Likely the invitation email itself, which can contain attachments.

**Comment by artojarvinen** [comment]
Yes, if I get a calendar invite email (proposed meeting) sent from Outlook without attachment(s), then everything works as it should. It immediately shows up in the TB calendar.

If the invite (again sent from Outlook) contains an attachment (like a pdf file) then it never shows in the TB calendar (not even if I accept it in some other client like Outlook). It does show up in my Outlook Webmail and Outlook clients though as it should. I've only tested it a couple of times but there seems to be a pattern here.

**Comment by ruohomaa-ericsson** [comment]
This explains what is up with seemingly inconsistent meeting invitation disappearance in my calendar as well. They all had attachments. Evolution is also able to show them so I'm juggling two email clients to work around this.

**Comment by ruohomaa-ericsson** [comment]
I can also confirm that the cache clearing workaround suggested in issue #203 does not get the event with an attachment to appear.

**Comment by advancingu** [comment]
@artojarvinen @ruohomaa-ericsson Please check `v5.0.0-alpha2` that I just released. If the issue is not fixed there, please reopen.

**Comment by Trim** [comment]
Well, that's a new issue: in the code, there was a wired attempt to create link attachment with the `http://somewhere` prefix. I've decided to replace it by `http://localhost` to prevent from running requests outside an unknown location.

So for me, the issue about "Event not showing" is well resolved, but there's an other with attachment: instead of using these domains, we should find the good one. I have no clue about what it should be, but I imagine that should be related to the Exchange Web Service URL.
