### ISSUE TITLE
THIS IS STRANGE in logs

### ISSUE THREAD

**Issue by wagner-certat** [ExchangeCalendar/exchangecalendar#211]
I observed these lines in the log:

```
ExchangeCalendar [2018-11-02T15:27:24.552Z]: [Sebastian Wagner]  THIS IS STRANGE beginDate (_performReset in mivExchangeCalendar.js:4378)
ExchangeCalendar [2018-11-02T15:27:24.554Z]: [Sebastian Wagner]  THIS IS STRANGE endDate (_performReset in mivExchangeCalendar.js:4385)
```

How could be find out more about this strangeness?

**Comment by advancingu** [comment]
There are many log messages in the code that look like coding was done without a debugger. I checked the origin of these messages and this happens at a location that might be relevant to the missing calendar entries. Since this is already covered in #203 I'm closing this here.

In case you want to debug an add-on yourself, please see https://stackoverflow.com/questions/10752584/how-to-debug-a-thunderbird-addon-extensions-javascript#18995941
