### ISSUE TITLE
All calendars readonly

### ISSUE THREAD

**Issue by NdK73** [ExchangeCalendar/exchangecalendar#57]
Hello all.

I configured my own calendar and some shared ones, but all are marked readonly.
Moreover, at start I get prompted for the password even if I already checked the box to use password manager. Tried both with and without NTLM-v1.

A strange thing I noticed is that username and domain are swapped: username/DOMAIN instead of DOMAIN\username .

Using 4.0.0.b4 with Lightning 5.4 on TB 52.2.1 (64 bit). Ubuntu 16.04.2 LTS.

Any hints?

Tks.

**Comment by Trim** [comment]
Hello,

To work with current TB 52.2.1 an external developper helped us by providing a patch to fix a password prompt issue.

Since then, some users have noticed that we have to log in with the new username style: "username@DOMAIN" instead of old style "DOMAIN\username".

When you configure your calendar, you can write in the username field "username@DOMAIN", then the domain field is grayed and you can continue configuration.

Maybe you are seeing same issue than others in  Ericsson/exchangecalendar#595 ?

**Comment by NdK73** [comment]
If I use username@DOMAIN (or DOMAIN\username, or email address) the mandatory check does not complete -- I see "1 running & 10 queued jobs" at the bottom of the main TB window.

I upgraded to 4.0.0b4 exactly because I was having that issue.
Too bad I have zero experience in writing plugins. If someone could point me in the right direction I could probably find some workaround...

**Comment by NdK73** [comment]
Seems that the issue was with some old data.
I removed subscription from the existing Exchange calendars, restarted TB and created a calendar from scratch, using username@DOMAIN : it worked!
Tomorrow I'll test with shared calendars.

**Comment by NdK73** [comment]
Seems that the issue was with some old data.
I removed subscription from the existing Exchange calendars, restarted TB and created a calendar from scratch, using username@DOMAIN : it worked!
Tomorrow I'll test with shared calendars.

**Comment by NdK73** [comment]
Shared calendars are working fine now.
