### ISSUE TITLE
Looking to contribute, but no idea where to start

### ISSUE THREAD

**Issue by retorquere** [ExchangeCalendar/exchangecalendar#6]
I'm familiar with XUL extension development, and I want to look into contributing to the extension. Specifically, I have this idea that the extension currently doesn't (effectively) uses EWS [delta sync](https://msdn.microsoft.com/en-us/library/office/dn440953(v=exchg.150).aspx) because I see fairly frequent updates drawn in the calendar. Is this idea I have true, and where should I start looking to implement delta sync?

**Comment by advancingu** [comment]
To be honest, I'm not sure myself what the best way is to start for this particular task. If you want to begin with something smaller, you could look at integrating one of the existing pull requests that are still open on the Ericsson/exchangecalendar repository and submitting them here with additional fixes as needed.

For the time being, I'm closing this ticket since it is not an issue in itself, however feel free to post additional comments.
