### ISSUE TITLE
Release of version 4.0.0

### ISSUE THREAD

**Issue by Mechtilde** [ExchangeCalendar/exchangecalendar#90]
Hello
What is your plan to release version 4.0.0. this can help me to plan the release in Debian.

Kind regards

Mechtilde

**Comment by Trim** [comment]
Hello,

In my opinion, before releasing version 4.0.0 we should:

* Finish installation of Transifex, so contributors will have better tools to help us
* Integrate a `Makefile` to build the project easily
* Complete update of the README to give updated informations to users

I know that's not related to code directly, but I think that's necessary to have a minimum set of tools to create a real community. With just these requirements, I think we can make a release in September 2017.

Some points which could be good to integrate too, will be:

1. Upgrade the console messages to redirect to our Github page instead of Ericsson
2. Remove the update notification and installation
3. Retrieve all contributors with `git log` and create a `COPYRIGHT` file as every one who modified the code have a copy right.
4. Update all files in the code with automatic indentation
5. Update directory structure to help hackers to find bugged code

This list of point will take more time and we can't integrate them in September. Points 4 and 5 will avoid us to easily receive new merge requests. I think we should integrate them in the 4.0.0 release, but it will certainly require to postpone release date to at least October.

Please note, that next ESR Firefox release will be in June 2018, so we can take time to integrate all these modifications, but I understand clearly that we can't let users without real release even if not perfect (there's already a lot of issues, especially ones about cache and performance, and for those we need to have more coders to help us).

**Comment by Mechtilde** [comment]
Hello,

using EWS with Thunderbird 52.x, you neew version 4.0.0. Thunderbird 52
is the actual ESR version so this version is now important.

EWS doesn't depend on Firefox but depend on Thnderbird.

At last weekend I released 4.0.0-beta4 for Debian-Backports (stable and
oldstable)

But it is better to have a final relase there. That is the background of
my question

Kind regards

-- 
Mechtilde Stehmann
## Debian Developer
## Loook, calender-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by Trim** [comment]
> EWS doesn't depend on Firefox but depend on Thnderbird.

Yes, indeed, but Thunderbird follow the ESR release cycle from Firefox :)

> At last weekend I released 4.0.0-beta4 for Debian-Backports (stable and oldstable)

Thanks !

> But it is better to have a final relase there. That is the background of my question

Yeah, I understand, I just wanted to help you to know why we don't release right now the new stable release: in summary, we need to finish our fork correctly, even if the code is almost working since beta4.

**Comment by advancingu** [comment]
@Mechtilde Thanks for getting in touch to coordinate. I agree with @Trim that more cleanup is needed before tagging this as a new major release. With that being said, please let us know in case we come close to missing any important deadlines.

**Comment by naevtamarkus** [comment]
So, I take from your comments that the functionality is there in the Beta4 without important bugs, right? So, for someone that thinks documentation is all-right and is not able to help in the coding (write PRs)... can we go for the Beta4 version?

**Comment by advancingu** [comment]
@naevtamarkus I don't think it is safe to say that there are no important bugs, in fact the code that I've seen so far is fairly horrible, so I'd rather say it is safe to say that there are a ton of important bugs hiding in the code. For example, I am suddenly not seeing any calendar entries anymore from our shared team calendar at work, even though I have full access.
The decision to call a 4.0 release is therefore primarily one of having some sort of consensus that the project is in "good enough shape".

**Comment by advancingu** [comment]
@Trim What is your opinion on releasing 4.0? It feels like all major pieces are in place.

**Comment by Trim** [comment]
IMHO, there's one last big step before having a good basis to release: we should update the code tree style as proposed in bug #80.

I'm working right now on the addresbook part and that's quiet straightforward, as this part has already been a bit split from the rest. There's also the "email tag" part which should be relatively fast to move.

**Comment by Trim** [comment]
Oh, yesterday, I've seen the PR #Ericsson/exchangecalendar/506 and I think we have to disable the code inside `default/preferences/debug.pref.js`, because it forces the global indexer to be enabled and it modifies some XUL properties.

I'll make a patch to disable all code inside this debug file and to add a message to say to user he should enable Global Search and Indexer in the Thunderbird Advanced settings to have a working « email tagging and invite calendar column in mail box » (according to the bavincen's comment).

I want to disable this file, because [this debugging howto](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XULRunner/Debugging_XULRunner_applications) explains that any files located in `%appname%/defaults/preferences/` and having `.js` extension is loaded on application start.

**Comment by advancingu** [comment]
[Version 4](https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v4.0.0) is already released now.
